baseURL = 'https://tung-tt.github.io/'
locale = 'en-us'
title = 'Tung Tran - 2026'
theme = 'hextra'

[menu]

    [[menu.main]]
        name = "Documentation"
        pageRef = "/docs"
        weight = 1

    [[menu.main]]
        name = "Blog"
        pageRef = "/blog"
        weight = 2
    
    [[menu.main]]
        name = "Github"
        url = "https://github.com/tung-tt"
        weight = 3
        [menu.main.params]
            icon = "github"
    
    [[menu.main]]
        name = "Search"
        weight = 4
        [menu.main.params]
            type = "search"
            
    # The Dark/Light Mode Toggle Button
    [[menu.main]]
        name = "Theme Toggle"
        weight = 5
        [menu.main.params]
            type = "theme-toggle"
